### ISSUE TITLE
在Vzense SDK 开发者指南 linux中 Ps2_SetWDROutputMode 这个函数第三个参数是否应该为in

### ISSUE THREAD

**Issue by 1278741833** [Vzense/Vzense_SDK_Linux#1]
在Vzense SDK 开发者指南 linux中 Ps2_SetWDROutputMode 这个函数第三个参数是否应该为in？是不是写错了
![image](https://user-images.githubusercontent.com/53327154/106439478-b34c2400-64b2-11eb-9c0c-a9c171159832.png)

**Comment by Teemovzense** [comment]
的确是写错了。
感谢您的指正！
