### ISSUE TITLE
The source name in the make file does not match the actual name

### ISSUE THREAD

**Issue by howyoungchen** [Vzense/Vzense_SDK_Linux#6]
The source name in the make file of [aarch64 ](https://github.com/Vzense/Vzense_SDK_Linux/tree/master/AArch64/Samples/DCAM550_Samples/02DeviceInfoGet)does not match the actual name.

```
TARGET := DeviceInfoGet

SOURCE := DeviceInfoGet.cpp

FLAGS := -I../../../Include -Wl,-rpath,./:../Lib/:../../../Lib/:-Wall -Wconversion -O3 -L../../../Lib -lvzense_api 
```

**Comment by neal-vzense** [comment]
Thanks for the comment, we have fixed it in 2022-08-19.
